name: Example Blurb
slug: example-blurb
groups: content
form:
  general:
    - name: title
      type: text
      help: The title of your blurb will appear based on your image/icon position settings.

    - name : link
      type : link
      value :
        url:
        target:
      help : If you would like to make your blurb a link, input your destination URL here.

    - name: icon_enabled
      type: switch
      label: Use Icon
      help: Here you can choose whether icon set below should be used.

    - name: icon
      type: icon
      depends:
        icon_enabled: true

    - name: image
      type: image
      depends:
        icon_enabled: false

    - name: image_alt_text
      type: text
      label: Image Alt Text
      help: Define the HTML ALT text for your image here.
      depends:
        icon_enabled: false

    - name: placement
      type: select
      label: Image/Icon Placement
      value: beforeTitle
      options:
        beforeTitle: Before Title
        afterTitle: After Title
        left: Left
        right: Right

    - name: animation
      type: select
      value: fadeIn
      label: Animation
      options:
        fadeInLeft: Left To Right
        fadeInRight: Right To Left
        fadeInUp: Bottom To Top
        fadeInDown: Top To Bottom
        fadeIn: Fade In
        zoomIn: Zoom In
        0: No Animation

    - name: animation_delay
      type: text
      value: 0.1
      help: Animation delay in second. Only number is acceptable.

    - name: content
      type: editor
      value: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.

    - name: alignment
      type: select
      label: Content Alignment
      value: center
      options:
        left: Left
        center: Center
        right: Right

  styles:
    - name: header_font
      type: typography
      label: Header Font

    - name: header_color
      type: color
      label: Header Text Color 

    - name: header_margin
      type: margin
      label: Header Margin

    - name: body_font
      type: typography
      label: Content Font

    - name: body_color
      type: color
      label: Content Text Color 

    - name: icon_font_size
      type: slider
      lable: Icon Font Size
      value : 80
      depends:
        icon_enabled: true

    - name: icon_color
      type: color
      label: Icon Color 
      depends:
        icon_enabled: true

    - name: bg_color
      type: color
      label: Background Color

    - name: bg_hover_color
      type: color
      label: Background Hover Color

    - name: bg_image
      type: image
      label: Background Image

    - name: image_repeat
      label: Image Repeat 
      type: select
      value: no-repeat
      depends:
        bg_image : '*'
      options: 
        no-repeat : No Repeat
        repeat-x : Repeat X 
        repeat-y : Repeat Y
        repeat: Repeat All

    - name: image_position
      type: select
      label: Image Position 
      value: initial
      depends:
        bg_image : '*'
      options:
        initial: Default
        center: Center
        top left : Top Left 
        top center : Top Center
        top right: Top Right
        center right: Center Right
        center left: Center Left
        bottom left: Bottom Left
        bottom center: Bottom Center
        bottom right: Bottom Right

    - name : image_size
      type : select
      label : Image Size
      value : initial
      depends:
        bg_image : '*'
      options :
        initial : Default
        cover : Cover 
        contain : Contain 
  
    - name: media_margin
      type: margin
      
    - name: border
      type: switch
      label: Use Border

    - name: border_width
      type: slider
      label: Border Width
      value: 2
      depends:
        border: true

    - name: border_radius
      type: slider
      label: Border Radius
      value: 3
      depends:
        border: true

    - name: border_style
      type: select
      value: solid
      depends:
        border: true
      options:
        solid: Solid
        dotted: Dotted
        dashed: Dashed
        double: Double
        groove: Groove
        ridge: Ridge
        inset: Inset
        outset: Outset

    - name: border_color
      type: color
      label: Border Color
      depends:
        border: true

    - name: border_hover_color
      type: color
      label: Border Hover Color
      depends:
        border: true

    - name: margin
      type: margin

    - name: padding
      type: padding
